### PR TITLE
Added a force option

### PR DESCRIPTION
**Pull request by KingOfBrian**
Working on updating our certs that expire in 3 days. cert wouldn't create a new cert if a valid one exists. This adds a force option like seen in sigh to create a cert regardless of state.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks good, thanks for the pull request :+1: This will be in the next release

**Comment by KingOfBrian** [comment]
Are you interested in adding a delete option to delete expired certificates @KrauseFx ? I'd like to be able to automatically regenerate my cert and provisioning profile every 6 months to avoid the mass re-signing. But with the expired one holding one of the 2 slots, this still requires me to log into iTunes Connect like an animal.

**Comment by KingOfBrian** [comment]
To be clear -- interested in me developing a switch for cert, not a request for you to add the feature ;)

**Comment by KingOfBrian** [comment]
Was easy enough to add, and having fun in ruby land -- #47

**Pull request merged**
