### PR TITLE
Revoke expired certificates

### PR DESCRIPTION
**Pull request by KingOfBrian**
This will revoke expired certs when a switch `--revoke_expired` has been specified. I have tested the logic, but won't be able to actually test it for another few days.

### CODE REVIEW

**Comment by KrauseFx** [comment]
That's great. I'd love to wait until this has been tested, please let me know once one of your certificates expired and if it works :+1: 
Thanks for your pull request

**Comment by KingOfBrian** [comment]
So. I forgot to try the script out, and someone cleared out the cert. Anyone brave souls with an expired cert out there? ( @jcampbell05 / @KrauseFx )

**Comment by jcampbell05** [comment]
I'll give it a shot, know a way of automatically creating a expired one ?

**Comment by KingOfBrian** [comment]
I don't. I'm sure most people have an expired cert sitting around, but I just cleared all mine out.

**Comment by mfurtak** [comment]
Hi @KingOfBrian - sorry for the long silence here. Given that it's been a while, how are you feeling about this? Is this still something you're looking to do through `cert`?

**Comment by KingOfBrian** [comment]
This should just work now I believe. I don't have any expired certs though so I can't test it out.

**Comment by mfurtak** [comment]
Merged as part of #70

**Pull request closed without merging**
